image: node:10.10.0

pages:
  cache:
    paths:
    - node_modules/
    - .cache/

  script:
  - npm install
  - npm run build

  artifacts:
    paths:
    - public
  
  only:
  - master